import { attacca, pausa } from './guida.mjs'
const p = await attacca()
await p.valuta(`location.reload(); return 1`); await pausa(3000)
await p.valuta(`[...document.querySelectorAll('a')].find(e => /To do|Da fare/.test(e.innerText)).click(); return 1`)
await pausa(1000)
console.log('1 · prima apertura, il giro compare:', await p.valuta(`return !!document.querySelector('[role="dialog"]')`) ? '✓' : '✗')
await p.tasto('Escape'); await pausa(1200)
const api = (via) => p.valuta(`return await (await fetch(${JSON.stringify(via)}, { headers: { authorization: 'Bearer sviluppo-non-in-produzione' } })).json()`)
console.log('2 · chiuso con Esc, segnato per l\'account:', (await api('/api/stato')).config.giro ? '✓' : '✗')
await p.valuta(`location.reload(); return 1`); await pausa(3000)
await p.valuta(`[...document.querySelectorAll('a')].find(e => /To do|Da fare/.test(e.innerText)).click(); return 1`)
await pausa(1000)
console.log('3 · ricaricato, NON ricompare:', await p.valuta(`return !!document.querySelector('[role="dialog"]')`) ? '✗ ricompare' : '✓')
p.chiudi(); process.exit(0)
